title: Yam K.Basnet
description: Senior Technical Specialist | SCCM | PCA | IDM | PAM | Digital Singature | IT Project | Automation
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
